### ISSUE TITLE
Add option to reencode stream before Prebuffer

### ISSUE THREAD

**Issue by macjl** [seydx/homebridge-camera-ui#316]
**Is your feature request related to a problem? Please describe.**
Hello, I have an (old) mjpeg Camera added to Homebridge-camera-ui v5.0.0-beta.55. All work well, except that I can't use the 'Prebuffer' option, as the stream is not H264 : 
`[CameraUI] Porche: Can not start Prebuffer, camera does not support H264 stream (mjpeg (Baseline), yuvj422p(pc, bt470bg/unknown/unknown), 640x480, 25 tbr, 25 tbn, 25 tbc)`

As the camera is pretty old, the option would be useful to open only one stream to it, instead of opening multiple that will slow down the camera (1 for motion analysis, 1 for HSV, etc....)

**Describe the solution you'd like**
Could you add an option to reencode the stream to H264 in the prebuffer process, instead of using the 'copy' codec ? That would be an optional parameter, because it's working well for cameras that natively support h264.

**Describe alternatives you've considered**
I tried to use the 'restreamer' project to reencode the stream in H264/RTMP before serving it to Camera-UI. It works, but add a long unnecessary delay.

**Comment by seydx** [comment]
Atm, reencoding only 1 stream with eg libx264 will also lead to very high cpu because the reencoding process will be done twice (prebuffering for HSV recordings, and prebuffering for fast stream)

![creating_multiple_outputs2](https://user-images.githubusercontent.com/34152761/148647024-9a188f42-d760-4aa7-9b2f-cdaa3e597b04.png)

I'll take a look to see if there is a better alternative for prebuffer with reencoding

**Comment by seydx** [comment]
v.5.0.0-beta.58 is online. 

To enable prebuffering for cameras without a h264, please enable also `forcePrebuffering` in your config.json. 

Im using the [tee pseudo-muxer](https://ffmpeg.org/ffmpeg-formats.html#tee) to encode only once for multiple outputs. In my tests, however, this also led to a high CPU load. So try with caution.

![creating_multiple_outputs1](https://user-images.githubusercontent.com/34152761/148651866-d71a3611-b6f5-4129-9cb6-ee8ee44f1edc.png)

vcodec will be "libx264" if not set in config, or if set to "copy"

**Comment by macjl** [comment]
Hello,

Thank for the option!

Do you confirm that with this option, I have  to set vcodec to copy, to avoid transcode the stream multiple times?

**Comment by seydx** [comment]
No. Let me explain. With prebuffering the streams are forwarded to 2 different outputs (one for HSV recordings and one for fast stream/snapshot  loading times). But if you have to reencode the streams (because your stream is not h264), then it was previously so that it had to reencode for each output individually.

Now, when the stream has to be reencoded, it happens only once for all outputs.

This causes less CPU usage. But still it was too high in my tests. Therefore try with caution
