### ISSUE TITLE
Camera not broadcasted if unbridge is selected

### ISSUE THREAD

**Issue by Garia666** [seydx/homebridge-camera-ui#415]
Hi i have gone trough the faq but still no resolve.
When i try to add a new accessory the Camera does not pop up. 

It is shown in the camera.ui and if i deselect the "Unbridge Camera" it will show up in the homekit.
Note*  cannot remove the camera anymore until you disable this plugin and then try again.  

Is this an known issue? i will RTF one more time to see if i maybe missed something

**Comment by seydx** [comment]
> Hi i have gone trough the faq but still no resolve. When i try to add a new accessory the Camera does not pop up.
> 
> It is shown in the camera.ui and if i deselect the "Unbridge Camera" it will show up in the homekit. Note* cannot remove the camera anymore until you disable this plugin and then try again.
> 
> Is this an known issue? i will RTF one more time to see if i maybe missed something

Hey @Garia666 

if unbridge is NOT enabled, you need to remove the bridge from Apple Home to also remove the camera because it is BRIDGED

It seems you have a caching issue with homebridge, change the name of you camera in your config.json to something unique, enable unbridge again and restart homebridge

After then, open the Home App and click „+“ to add a new accessory. You should now see your camera, the PIN is the same as from your Homebridge

**Comment by seydx** [comment]
See https://github.com/seydx/homebridge-camera-ui/wiki/FAQ#i-can-not-see-the-cameras-in-apple-home

**Comment by Garia666** [comment]
**change the name of you camera in your config.json**

This!  thanks allot man this should be added as an solution on the FAQ

anyway it works  thanks allot for the quick reply!

ill do an small donation for your efforts

**Comment by seydx** [comment]
> **change the name of you camera in your config.json**
> 
> This! thanks allot man this should be added as an solution on the FAQ
> 
> anyway it works thanks allot for the quick reply!
> 
> ill do an small donation for your efforts

Thank you very much for the donation

This is already in the FAQ 😄

see https://github.com/seydx/homebridge-camera-ui/wiki/FAQ#i-can-not-see-the-cameras-in-apple-home
