### ISSUE TITLE
Anyone willing to share their detection setups that work well for HKSV?

### ISSUE THREAD

**Issue by tbelcher** [seydx/homebridge-camera-ui#421]
Like some other users, I find that HKSV detection doesn't catch all the events that the native Wyze app does and I'm wondering if there are settings that seem to work well.  I've messed around in the Camera/VideoAnalysis with dwell time, sensitivity, and pixel/color difference but I can't seem to find the right settings.  Currently mine are:

Dwell Time: 60
Reset motion: 3
Sensitivity: 94
Pixel/color difference: 3

Thanks

**Comment by eRJe79** [comment]
I started playing with this just a few days ago. Still playing around with he setup but the HKSV works pretty well with the default settings. It seems to capture all motions, spitting out person, vehicle or occasionally a face recognition. 

Dwell Time: 60
Reset motion: 3
Sensitivity: 75
Pixel/color difference: 5

I did notice that HKVS stopped working a few times. Once over night without touching the setup. I found that starting from scratch again was the best way get it working again. The first setup was on a RPI 3b which was clearly struggling on CPU. That caused camera.ui to miss motion completely. I'm now running on a Debian VM with Docker.

For my test I am using a single Hikvision 4K camera with the main stream reduced to HD (1920x1080). HKVS is set to Stream and Recording when at home or away. I'm highly surprised this works for me since my upload speed is close to nothing.

Overall I do experience choppy video recoding.

**Comment by LutianoFTW** [comment]
Played quite a bit with those settings and the best settings varies per camera type (i run two hikvision 4k cameras and a video doorbell)

For the two cameras high end cameras i have the following settings:

Dwell time: 75
Reset motion after: 0 (this works great, sometimes i missed some movement but i found out that the movement was overlapping and due to the reset timer some movement was not recorded by putting it on 0 the problem with missing movement is gone)

Sensitivity: 83 (not think that something went wrong in your settings if you see a recording with for example sensitivity 79, the number you give here is a maximum of sensitivity, it detects movement till 83 sensitivity and under that value, all above is not seen as "movement")
This setting is something to play with and simply works with trail and error.

Pixel/color difference: 4

To get a good speed of your streams check your camera settings directly at the ip of the camera, when you directly put it in that menu on h264 it will speed up the stream a lot because h264 is supported by homekit and it avoids complex decoding.

Put the following in front of your stream link helps also speeding up the stream (after of course performed the step above)

-rtsp_transport tcp -re -i rtsp://username:password@ipofcamera:554/Streaming/Channels/101/

Username:password - put here the username and password of the camera
Behind @ put the ip of the camera

After filling the missing information and using the links the stream should already been faster.
