### ISSUE TITLE
FFmpeg process 

### ISSUE THREAD

**Issue by SeydX** [SeydX/homebridge-camera-ui#51]
It seems, that some user (atm only macOS) has problems with hanging ffmpeg processes.

If you are also using macOS and has problems with hanging ffmpeg processes, pls report it here!

Every log, screenshot or anything else that helps me to debug is welcome!

I also need the information about the operating system, Homebridge version and CameraUI version

SeydX

**Comment by SeydX** [comment]
It looks like a FFmpeg process will only hang if several FFmpeg requests for the same camera are happening at the same time. This can be the case when the user is watching the livestream in the interface, a recording is running in the background because motion is detected and when the user or multiple users are watching the stream in Apple Home.

One solution would be to add a kind of timeout to terminate processes that have hung up.

**Comment by SeydX** [comment]
Possible solution

```
-timeout
Set maximum timeout (in seconds) to wait 
for incoming connections.

A value of -1 means infinite (default). 
This option implies the rtsp_flags set 
to ‘listen’.
```

**Comment by SeydX** [comment]
Added a new function called "streamSessions"  https://github.com/SeydX/homebridge-camera-ui/commit/9f3b3b8530a125570f3251e56819ef0c8155e5ad

This should handle ffmpeg processes for each camera through ui and plugin and avoid this issues

Todo:
Also add ``-timeout`` ?

**Comment by BertoTavira** [comment]
Hi, since Homebridge 1.3.0 I’m having a lot of issues with my cameras.
I know it could be they’re also slow (Yi Cloud Dome with yi-hack-v4 and Yi Home 1080 with yi-hack-allwinner), but with previous version the overall experience was better.
Now I got always the notification of being _too slow!_ or _not providing image buffer!_ or _didn’t responding at all!_
Also got too frequently the issue of max streams reached and increasing the number doesn’t seem to fix it, since eventually ffmpeg processes get to that amount sooner or later.

Is it just me or is happening to more users?
Could -timeout be implemented too as you asked?
Maybe that way ffmpeg processes can be shut down after some reasonable time
