### ISSUE TITLE
ffmpeg error on macOS

### ISSUE THREAD

**Issue by schwie** [seydx/homebridge-camera-ui#536]
Hello, I tried installing homebridge-camera-ui today through homebridge-ui on a Mac running Monterey. Several other plugins are installed on homebridge on this Mac and they all work fine. Prior to installing homebridge-camera-ui a copy of the plugin homebridge-camera-ffmpeg was installed and it was working fine before it was removed to make way for homebridge-camera-ui.

homebridge-camera-ui installs just fine on my Mac, but when I try to add any camera, even [using your generic settings](https://github.com/SeydX/homebridge-camera-ui/blob/master/example-config.json), the homebridge-camera-ui pluggin begins causing homebridge to crash and restart continuously - see homebridge log showing crash in screenshot below. The minute all cameras are removed from homebridge-camera-ui, homebridge no longer crashes.

I'd love to start adding cameras to homebridge-camera-ui on this Mac, but right now the log indicates ffmpeg may be the culprit (see ENOENT error, below). Also, please see the default installation location for ffmpeg in the screenshots below, should an ffmpeg binary be visible/installed here? Is there anything else I can look for? Does the config.json file need to be hardcoded with the path for ffmpeg?

<img width="716" alt="homebridge_log_errors" src="https://user-images.githubusercontent.com/676113/164793110-5b144b4e-2d58-4f90-bb0d-01fad5a4f3eb.png">

![location](https://user-images.githubusercontent.com/676113/164793128-da7f058c-9d1a-486f-8ccc-1d20a78f7d7d.jpg)

![folder contents](https://user-images.githubusercontent.com/676113/164793420-d19c8b11-fb5b-4ed6-9e4f-3ea9f5904d52.jpg)

**Environment**
- Node.js Version: v16.13.2
- Homebridge Version: v1.4.0
- Camera UI Version: v5.0.20
- Operating System: Monterey 12.3.1
- Browser: Safari v. 15.4

**Comment by seydx** [comment]
Hey @schwie 

its because `ffmpeg-for-homebridge` is not compatible with Mac, but you can use your own ffmpeg (if installed on your system) with following config entry:


```json
"options": {
  "videoProcessor": "ffmpeg"
}
```

_see: https://github.com/seydx/homebridge-camera-ui/blob/bde4af5e041602dac0c821eaa9d1a593518f42f1/example-config.json#L44)

Or you can download `ffmpeg-for-homebridge` for your mac and put it into the `ffmpeg-for-homebridge` directory

Download Link: https://github.com/homebridge/ffmpeg-for-homebridge/files/7530459/ffmpeg.zip
