### ISSUE TITLE
Password Reset

### ISSUE THREAD

**Issue by frizby66** [seydx/homebridge-camera-ui#590]
Have searched and cant find out how to reset the password? Any pointers?

**Comment by Hackintoshbigsur** [comment]
I'm Pretty Sure there's a file for it that you have to edit.

**Comment by frizby66** [comment]
I could see anything obvious! Any pointers from anyone?

**Comment by Hackintoshbigsur** [comment]
Dry Saving the config and re-installing the plugin.

**Comment by frizby66** [comment]
Tried uninstall and reinstall...didnt work, still cant get into the interface :-(

**Comment by FinocchiaroGR** [comment]
I used the suggested password my MacBook gave me to create the new user, and when logging in for the first time with my finger print, it told me the password was wrong..... so much security but no way to reset my password? no even if I'm inside the local network of my home? there is no documentation about it anywhere on internet. :'(

**Comment by Finch106** [comment]
WARNING Interface: Failed login attempt! If you have forgotten your password you can reset to the default of
master/master by removing the user in the "database. json" file (/var/lib/homebridge/camera.ui/database/database.json and then restarting camera.ui

**Comment by frizby66** [comment]
Tried that...doesnt appear to work. Still the same..found the user in the json and deleted the user. Also tried deleting the user folder.

**Comment by HelmerBarcos** [comment]
The problem is that the file `/var/lib/homebridge/camera.ui/database/database.json ` is been modified to the default values if `homebridge` and `Homebridge Camera Ui` are running. To solve this you need to:

1. Deactivate `Homebridge Camera Ui` under `http://homebridge.local/plugins`
2. Run `sudo hb-service stop` inside the ubuntu server
3. Edit the file by adding following object to under `users : [ ... ]` (edit the value of the `id` if other users were stored)
```
{
      "id": 2,
      "username": "master",
      "password": "JzUVQgmHtgXXT1syjbokEQ==$t4U9BUwDoeXNtxpgzi4DXwFIU2AXgq9QyoFQkImEyfPmx/mxg/a1snxyOhK8dvgtytjO1KkZ2sCbjzmgW8jPQQ==",
      "sessionTimer": 14400,
      "photo": "no_img.png",
      "permissionLevel": [
        "admin"
      ]
}

```

4. Save the file
5. Run `sudo hb-service start` inside the ubuntu server
6. Activate `Homebridge Camera Ui` under `http://homebridge.local/plugins`
7. Try to login with default credentials. `username` = master and `password` = master

**Comment by Longkho** [comment]
For macOS user look for the ~/.homebridge/camera.ui/database which should have database.json and <user> dir.
Then locate the "users" under the database.json

  "users": [
    {
      "id": 1,
      "username": "master",
      "password": "JzUVQgmHtgXXT1syjbokEQ==$t4U9BUwDoeXNtxpgzi4DXwFIU2AXgq9QyoFQkImEyfPmx/mxg/a1snxyOhK8dvgtytjO1KkZ2sCbjzmgW8jPQQ==",
      "sessionTimer": 14400,
      "photo": "no_img.png",
      "permissionLevel": [
        "admin"
      ]
    }
  ],

use the password as "master" to login but do remember to change the username/password as camera.ui will not ask you to change the password.
